import Foundation

extension AppStrings {
    static let supplementalLocalizedValues: [AppLanguage: [String: String]] = [
        .ja: [
            "terminalTheme": "ターミナルテーマ",
            "terminalTheme.classicGreen": "クラシックグリーン",
            "terminalTheme.amber": "アンバー",
            "terminalTheme.paperWhite": "ペーパーホワイト",
            "terminalTheme.ocean": "オーシャン",
            "recent": "最近",
            "clearHistory": "履歴を消去",
            "importConnections": "インポート",
            "exportConnections": "エクスポート",
            "importConnectionsFailedFormat": "接続のインポートに失敗しました: %@",
            "exportConnectionsFailedFormat": "接続のエクスポートに失敗しました: %@",
            "loadConnectionsFailedFormat": "接続の読み込みに失敗しました。現在の一覧は保持されました: %@",
            "noConnections": "接続なし",
            "addToFavorites": "お気に入りに追加",
            "removeFromFavorites": "お気に入りから削除",
            "alias": "別名",
            "group": "グループ",
            "host": "ホスト",
            "port": "ポート",
            "username": "ユーザー名",
            "tags": "タグ",
            "usePrivateKey": "秘密鍵を使用",
            "privateKeyPath": "秘密鍵のパス",
            "privateKeyPassphrase": "秘密鍵のパスフレーズ",
            "password": "パスワード",
            "connection": "接続",
            "keepConnectionAlive": "接続を維持",
            "aliveIntervalSeconds": "キープアライブ間隔（秒）",
            "aliveMaxCount": "キープアライブ最大回数",
            "jumpHost": "ジャンプホスト",
            "defaultRemotePath": "デフォルトのリモートパス",
            "portForwarding": "ポート転送",
            "enableForwarding": "転送を有効化",
            "type": "種類",
            "local": "ローカル",
            "remote": "リモート",
            "dynamic": "ダイナミック",
            "bindAddress": "バインドアドレス",
            "destinationHost": "宛先ホスト",
            "destinationPort": "宛先ポート",
            "trustHostKeyTitle": "SSH ホスト鍵を信頼しますか？",
            "reject": "拒否",
            "trust": "信頼",
            "toggleConnections": "接続パネルを切り替え",
            "toggleSFTPDrawer": "SFTP パネルを切り替え",
            "commandSnippets": "コマンドスニペット",
            "listFiles": "ファイル一覧",
            "diskUsage": "ディスク使用量",
            "memoryUsage": "メモリ使用量",
            "processMonitor": "プロセスモニター",
            "serverStatus": "サーバー状態",
            "smallerFont": "フォントを小さく",
            "largerFont": "フォントを大きく",
            "fontSize": "フォントサイズ",
            "refresh": "更新",
            "connectSFTP": "SFTP 接続",
            "parentDirectory": "親ディレクトリ",
            "remotePath": "リモートパス",
            "newFolder": "新規フォルダ",
            "rename": "名前変更",
            "name": "名前",
            "open": "開く",
            "done": "完了",
            "failed": "失敗",
            "cancelled": "キャンセル済み",
            "queued": "待機中",
            "running": "実行中",
            "retry": "再試行",
            "renameTab": "タブ名を変更",
            "title": "タイトル",
            "close": "閉じる",
            "copy": "コピー",
            "paste": "貼り付け",
            "showTermTP": "TermTP を表示",
            "quitTermTP": "TermTP を終了",
            "view": "表示",
            "welcomeTitle": "ようこそ",
            "welcomeMessage": "TermTP へようこそ\n\nサイドバーから接続を選んで SSH セッションを開始してください。",
            "connectingTo": "接続中",
            "connectedTo": "接続しました",
            "failedToConnect": "接続に失敗しました",
            "noActiveSSHSession": "有効な SSH セッションがありません",
            "sftpUnsupportedForConnection": "この接続では SFTP ファイル管理を使用できません",
            "sftpPasswordTitle": "SFTP パスワードを入力",
            "sftpPasswordMessage": "ターミナルは接続済みです。下のファイル管理を有効にするため、パスワードを一度入力してください。",
            "savePassword": "パスワードを保存",
            "sftpRefreshFailedFormat": "リモートファイルの更新に失敗しました: %@",
            "connectionTimedOutFormat": "接続が %@ 秒でタイムアウトしました"
        ],
        .ko: [
            "terminalTheme": "터미널 테마",
            "terminalTheme.classicGreen": "클래식 그린",
            "terminalTheme.amber": "앰버",
            "terminalTheme.paperWhite": "페이퍼 화이트",
            "terminalTheme.ocean": "오션",
            "recent": "최근",
            "clearHistory": "기록 지우기",
            "importConnections": "가져오기",
            "exportConnections": "내보내기",
            "importConnectionsFailedFormat": "연결 가져오기 실패: %@",
            "exportConnectionsFailedFormat": "연결 내보내기 실패: %@",
            "loadConnectionsFailedFormat": "연결을 불러오지 못했습니다. 현재 목록은 유지되었습니다: %@",
            "noConnections": "연결 없음",
            "addToFavorites": "즐겨찾기에 추가",
            "removeFromFavorites": "즐겨찾기에서 제거",
            "alias": "별칭",
            "group": "그룹",
            "host": "호스트",
            "port": "포트",
            "username": "사용자 이름",
            "tags": "태그",
            "usePrivateKey": "개인 키 사용",
            "privateKeyPath": "개인 키 경로",
            "privateKeyPassphrase": "개인 키 암호",
            "password": "비밀번호",
            "connection": "연결",
            "keepConnectionAlive": "연결 유지",
            "aliveIntervalSeconds": "유지 간격(초)",
            "aliveMaxCount": "연결 유지 최대 횟수",
            "jumpHost": "점프 호스트",
            "defaultRemotePath": "기본 원격 경로",
            "portForwarding": "포트 포워딩",
            "enableForwarding": "전달 활성화",
            "type": "유형",
            "local": "로컬",
            "remote": "원격",
            "dynamic": "동적",
            "bindAddress": "바인드 주소",
            "destinationHost": "대상 호스트",
            "destinationPort": "대상 포트",
            "trustHostKeyTitle": "SSH 호스트 키를 신뢰할까요?",
            "reject": "거부",
            "trust": "신뢰",
            "toggleConnections": "연결 패널 전환",
            "toggleSFTPDrawer": "SFTP 패널 전환",
            "commandSnippets": "명령 스니펫",
            "listFiles": "파일 목록",
            "diskUsage": "디스크 사용량",
            "memoryUsage": "메모리 사용량",
            "processMonitor": "프로세스 모니터",
            "serverStatus": "서버 상태",
            "smallerFont": "글꼴 작게",
            "largerFont": "글꼴 크게",
            "fontSize": "글꼴 크기",
            "refresh": "새로고침",
            "connectSFTP": "SFTP 연결",
            "parentDirectory": "상위 폴더",
            "remotePath": "원격 경로",
            "newFolder": "새 폴더",
            "rename": "이름 변경",
            "name": "이름",
            "open": "열기",
            "done": "완료",
            "failed": "실패",
            "cancelled": "취소됨",
            "queued": "대기 중",
            "running": "실행 중",
            "retry": "다시 시도",
            "renameTab": "탭 이름 변경",
            "title": "제목",
            "close": "닫기",
            "copy": "복사",
            "paste": "붙여넣기",
            "showTermTP": "TermTP 보기",
            "quitTermTP": "TermTP 종료",
            "view": "보기",
            "welcomeTitle": "환영합니다",
            "welcomeMessage": "TermTP에 오신 것을 환영합니다\n\n사이드바에서 연결을 선택해 SSH 세션을 시작하세요.",
            "connectingTo": "연결 중",
            "connectedTo": "연결됨",
            "failedToConnect": "연결 실패",
            "noActiveSSHSession": "활성 SSH 세션이 없습니다",
            "sftpUnsupportedForConnection": "이 연결은 SFTP 파일 관리를 지원하지 않습니다",
            "sftpPasswordTitle": "SFTP 비밀번호 입력",
            "sftpPasswordMessage": "터미널은 연결되어 있습니다. 아래 파일 관리를 사용하려면 비밀번호를 한 번 입력하세요.",
            "savePassword": "비밀번호 저장",
            "sftpRefreshFailedFormat": "원격 파일 새로고침 실패: %@",
            "connectionTimedOutFormat": "%@초 후 연결 시간이 초과되었습니다"
        ],
        .es: [
            "terminalTheme": "Tema del terminal",
            "terminalTheme.classicGreen": "Verde clásico",
            "terminalTheme.amber": "Ámbar",
            "terminalTheme.paperWhite": "Blanco papel",
            "terminalTheme.ocean": "Océano",
            "recent": "Recientes",
            "clearHistory": "Borrar historial",
            "importConnections": "Importar",
            "exportConnections": "Exportar",
            "importConnectionsFailedFormat": "No se pudieron importar las conexiones: %@",
            "exportConnectionsFailedFormat": "No se pudieron exportar las conexiones: %@",
            "loadConnectionsFailedFormat": "No se pudieron cargar las conexiones. Se conservó la lista actual: %@",
            "noConnections": "Sin conexiones",
            "addToFavorites": "Añadir a favoritos",
            "removeFromFavorites": "Quitar de favoritos",
            "alias": "Nombre corto",
            "group": "Grupo",
            "host": "Servidor",
            "port": "Puerto",
            "username": "Usuario",
            "tags": "Etiquetas",
            "usePrivateKey": "Usar clave privada",
            "privateKeyPath": "Ruta de clave privada",
            "privateKeyPassphrase": "Frase de clave privada",
            "password": "Contraseña",
            "connection": "Conexión",
            "keepConnectionAlive": "Mantener conexión activa",
            "aliveIntervalSeconds": "Intervalo de actividad (s)",
            "aliveMaxCount": "Reintentos de keepalive",
            "jumpHost": "Servidor de salto",
            "defaultRemotePath": "Ruta remota predeterminada",
            "portForwarding": "Reenvío de puertos",
            "enableForwarding": "Activar reenvío",
            "type": "Tipo",
            "dynamic": "Dinámico",
            "bindAddress": "Dirección de escucha",
            "destinationHost": "Host de destino",
            "destinationPort": "Puerto de destino",
            "trustHostKeyTitle": "¿Confiar en la clave SSH del host?",
            "reject": "Rechazar",
            "trust": "Confiar",
            "toggleConnections": "Mostrar/Ocultar conexiones",
            "toggleSFTPDrawer": "Mostrar/Ocultar panel SFTP",
            "commandSnippets": "Fragmentos de comandos",
            "listFiles": "Listar archivos",
            "diskUsage": "Uso de disco",
            "memoryUsage": "Uso de memoria",
            "processMonitor": "Monitor de procesos",
            "serverStatus": "Estado del servidor",
            "smallerFont": "Reducir fuente",
            "largerFont": "Aumentar fuente",
            "fontSize": "Tamaño de fuente",
            "refresh": "Actualizar",
            "connectSFTP": "Conectar SFTP",
            "parentDirectory": "Carpeta superior",
            "remotePath": "Ruta remota",
            "newFolder": "Nueva carpeta",
            "rename": "Renombrar",
            "name": "Nombre",
            "open": "Abrir",
            "done": "Completado",
            "failed": "Fallido",
            "cancelled": "Cancelado",
            "queued": "En cola",
            "running": "En curso",
            "retry": "Reintentar",
            "renameTab": "Renombrar pestaña",
            "title": "Título",
            "close": "Cerrar",
            "copy": "Copiar",
            "paste": "Pegar",
            "showTermTP": "Mostrar TermTP",
            "quitTermTP": "Salir de TermTP",
            "view": "Vista",
            "welcomeTitle": "Bienvenido",
            "welcomeMessage": "Bienvenido a TermTP\n\nSelecciona una conexión en la barra lateral para iniciar una sesión SSH.",
            "connectingTo": "Conectando a",
            "connectedTo": "Conectado a",
            "failedToConnect": "No se pudo conectar a",
            "noActiveSSHSession": "No hay sesión SSH activa",
            "sftpUnsupportedForConnection": "Esta conexión no admite gestión de archivos SFTP",
            "sftpPasswordTitle": "Introduce la contraseña SFTP",
            "sftpPasswordMessage": "La terminal ya está conectada. Introduce la contraseña una vez para activar la gestión de archivos.",
            "savePassword": "Guardar contraseña",
            "sftpRefreshFailedFormat": "No se pudieron actualizar los archivos remotos: %@",
            "connectionTimedOutFormat": "La conexión agotó el tiempo tras %@ segundos"
        ],
        .fr: [
            "terminalTheme": "Thème du terminal",
            "terminalTheme.classicGreen": "Vert classique",
            "terminalTheme.amber": "Ambre",
            "terminalTheme.paperWhite": "Blanc papier",
            "terminalTheme.ocean": "Océan",
            "recent": "Récents",
            "clearHistory": "Effacer l’historique",
            "importConnections": "Importer",
            "exportConnections": "Exporter",
            "importConnectionsFailedFormat": "Échec de l’import des connexions : %@",
            "exportConnectionsFailedFormat": "Échec de l’export des connexions : %@",
            "loadConnectionsFailedFormat": "Échec du chargement des connexions. La liste actuelle a été conservée : %@",
            "noConnections": "Aucune connexion",
            "addToFavorites": "Ajouter aux favoris",
            "removeFromFavorites": "Retirer des favoris",
            "alias": "Nom court",
            "group": "Groupe",
            "host": "Hôte",
            "port": "Port",
            "username": "Nom d’utilisateur",
            "tags": "Étiquettes",
            "usePrivateKey": "Utiliser une clé privée",
            "privateKeyPath": "Chemin de la clé privée",
            "privateKeyPassphrase": "Phrase secrète de la clé",
            "password": "Mot de passe",
            "connection": "Connexion",
            "keepConnectionAlive": "Garder la connexion active",
            "aliveIntervalSeconds": "Intervalle keepalive (s)",
            "aliveMaxCount": "Nombre maximal de keepalive",
            "jumpHost": "Hôte bastion",
            "defaultRemotePath": "Chemin distant par défaut",
            "portForwarding": "Redirection de ports",
            "enableForwarding": "Activer la redirection",
            "type": "Type",
            "local": "Local",
            "remote": "Distant",
            "dynamic": "Dynamique",
            "bindAddress": "Adresse d’écoute",
            "destinationHost": "Hôte de destination",
            "destinationPort": "Port de destination",
            "trustHostKeyTitle": "Faire confiance à la clé SSH de l’hôte ?",
            "reject": "Refuser",
            "trust": "Faire confiance",
            "toggleConnections": "Afficher/Masquer les connexions",
            "toggleSFTPDrawer": "Afficher/Masquer le panneau SFTP",
            "commandSnippets": "Extraits de commandes",
            "listFiles": "Lister les fichiers",
            "diskUsage": "Utilisation du disque",
            "memoryUsage": "Utilisation mémoire",
            "processMonitor": "Moniteur de processus",
            "serverStatus": "État du serveur",
            "smallerFont": "Réduire la police",
            "largerFont": "Agrandir la police",
            "fontSize": "Taille de police",
            "refresh": "Actualiser",
            "connectSFTP": "Connecter SFTP",
            "parentDirectory": "Dossier parent",
            "remotePath": "Chemin distant",
            "newFolder": "Nouveau dossier",
            "rename": "Renommer",
            "name": "Nom",
            "open": "Ouvrir",
            "done": "Terminé",
            "failed": "Échec",
            "cancelled": "Annulé",
            "queued": "En file",
            "running": "En cours",
            "retry": "Réessayer",
            "renameTab": "Renommer l’onglet",
            "title": "Titre",
            "close": "Fermer",
            "copy": "Copier",
            "paste": "Coller",
            "showTermTP": "Afficher TermTP",
            "quitTermTP": "Quitter TermTP",
            "view": "Affichage",
            "welcomeTitle": "Bienvenue",
            "welcomeMessage": "Bienvenue dans TermTP\n\nSélectionnez une connexion dans la barre latérale pour démarrer une session SSH.",
            "connectingTo": "Connexion à",
            "connectedTo": "Connecté à",
            "failedToConnect": "Échec de connexion à",
            "noActiveSSHSession": "Aucune session SSH active",
            "sftpUnsupportedForConnection": "Cette connexion ne prend pas en charge la gestion de fichiers SFTP",
            "sftpPasswordTitle": "Saisir le mot de passe SFTP",
            "sftpPasswordMessage": "Le terminal est connecté. Saisissez le mot de passe une fois pour activer la gestion de fichiers.",
            "savePassword": "Enregistrer le mot de passe",
            "sftpRefreshFailedFormat": "Échec de l’actualisation des fichiers distants : %@",
            "connectionTimedOutFormat": "Connexion expirée après %@ secondes"
        ],
        .de: [
            "terminalTheme": "Terminal-Design",
            "terminalTheme.classicGreen": "Klassisches Grün",
            "terminalTheme.amber": "Bernstein",
            "terminalTheme.paperWhite": "Papierweiß",
            "terminalTheme.ocean": "Ozean",
            "recent": "Zuletzt",
            "clearHistory": "Verlauf löschen",
            "importConnections": "Importieren",
            "exportConnections": "Exportieren",
            "importConnectionsFailedFormat": "Verbindungen konnten nicht importiert werden: %@",
            "exportConnectionsFailedFormat": "Verbindungen konnten nicht exportiert werden: %@",
            "loadConnectionsFailedFormat": "Verbindungen konnten nicht geladen werden. Die aktuelle Liste wurde behalten: %@",
            "noConnections": "Keine Verbindungen",
            "addToFavorites": "Zu Favoriten hinzufügen",
            "removeFromFavorites": "Aus Favoriten entfernen",
            "alias": "Kurzname",
            "group": "Gruppe",
            "host": "Host",
            "port": "Port",
            "username": "Benutzername",
            "tags": "Tags",
            "usePrivateKey": "Privaten Schlüssel verwenden",
            "privateKeyPath": "Pfad zum privaten Schlüssel",
            "privateKeyPassphrase": "Passphrase des Schlüssels",
            "password": "Passwort",
            "connection": "Verbindung",
            "keepConnectionAlive": "Verbindung aktiv halten",
            "aliveIntervalSeconds": "Keepalive-Intervall (s)",
            "aliveMaxCount": "Maximale Keepalive-Anzahl",
            "jumpHost": "Jump-Host",
            "defaultRemotePath": "Standard-Remotepfad",
            "portForwarding": "Portweiterleitung",
            "enableForwarding": "Weiterleitung aktivieren",
            "type": "Typ",
            "local": "Lokal",
            "remote": "Entfernt",
            "dynamic": "Dynamisch",
            "bindAddress": "Bind-Adresse",
            "destinationHost": "Zielhost",
            "destinationPort": "Zielport",
            "trustHostKeyTitle": "SSH-Hostschlüssel vertrauen?",
            "reject": "Ablehnen",
            "trust": "Vertrauen",
            "toggleConnections": "Verbindungen ein-/ausblenden",
            "toggleSFTPDrawer": "SFTP-Bereich ein-/ausblenden",
            "commandSnippets": "Befehlsbausteine",
            "listFiles": "Dateien auflisten",
            "diskUsage": "Festplattennutzung",
            "memoryUsage": "Speichernutzung",
            "processMonitor": "Prozessmonitor",
            "serverStatus": "Serverstatus",
            "smallerFont": "Schrift kleiner",
            "largerFont": "Schrift größer",
            "fontSize": "Schriftgröße",
            "refresh": "Aktualisieren",
            "connectSFTP": "SFTP verbinden",
            "parentDirectory": "Übergeordneter Ordner",
            "remotePath": "Remotepfad",
            "newFolder": "Neuer Ordner",
            "rename": "Umbenennen",
            "name": "Name",
            "open": "Öffnen",
            "done": "Fertig",
            "failed": "Fehlgeschlagen",
            "cancelled": "Abgebrochen",
            "queued": "Wartend",
            "running": "Läuft",
            "retry": "Erneut versuchen",
            "renameTab": "Tab umbenennen",
            "title": "Titel",
            "close": "Schließen",
            "copy": "Kopieren",
            "paste": "Einfügen",
            "showTermTP": "TermTP anzeigen",
            "quitTermTP": "TermTP beenden",
            "view": "Ansicht",
            "welcomeTitle": "Willkommen",
            "welcomeMessage": "Willkommen bei TermTP\n\nWählen Sie links eine Verbindung aus, um eine SSH-Sitzung zu starten.",
            "connectingTo": "Verbinde mit",
            "connectedTo": "Verbunden mit",
            "failedToConnect": "Keine Verbindung zu",
            "noActiveSSHSession": "Keine aktive SSH-Sitzung",
            "sftpUnsupportedForConnection": "Diese Verbindung unterstützt keine SFTP-Dateiverwaltung",
            "sftpPasswordTitle": "SFTP-Passwort eingeben",
            "sftpPasswordMessage": "Das Terminal ist verbunden. Geben Sie das Passwort einmal ein, um die Dateiverwaltung zu aktivieren.",
            "savePassword": "Passwort speichern",
            "sftpRefreshFailedFormat": "Remotedateien konnten nicht aktualisiert werden: %@",
            "connectionTimedOutFormat": "Verbindung nach %@ Sekunden abgelaufen"
        ],
        .ru: [
            "terminalTheme": "Тема терминала",
            "terminalTheme.classicGreen": "Классический зелёный",
            "terminalTheme.amber": "Янтарная",
            "terminalTheme.paperWhite": "Бумажно-белая",
            "terminalTheme.ocean": "Океан",
            "recent": "Недавние",
            "clearHistory": "Очистить историю",
            "importConnections": "Импорт",
            "exportConnections": "Экспорт",
            "importConnectionsFailedFormat": "Не удалось импортировать подключения: %@",
            "exportConnectionsFailedFormat": "Не удалось экспортировать подключения: %@",
            "loadConnectionsFailedFormat": "Не удалось загрузить подключения. Текущий список сохранён: %@",
            "noConnections": "Нет подключений",
            "addToFavorites": "Добавить в избранное",
            "removeFromFavorites": "Удалить из избранного",
            "alias": "Псевдоним",
            "group": "Группа",
            "host": "Хост",
            "port": "Порт",
            "username": "Имя пользователя",
            "tags": "Теги",
            "usePrivateKey": "Использовать приватный ключ",
            "privateKeyPath": "Путь к приватному ключу",
            "privateKeyPassphrase": "Парольная фраза ключа",
            "password": "Пароль",
            "connection": "Подключение",
            "keepConnectionAlive": "Поддерживать подключение",
            "aliveIntervalSeconds": "Интервал keepalive (с)",
            "aliveMaxCount": "Макс. число keepalive",
            "jumpHost": "Промежуточный хост",
            "defaultRemotePath": "Удалённый путь по умолчанию",
            "portForwarding": "Перенаправление портов",
            "enableForwarding": "Включить проброс",
            "type": "Тип",
            "local": "Локальный",
            "remote": "Удалённый",
            "dynamic": "Динамический",
            "bindAddress": "Адрес прослушивания",
            "destinationHost": "Хост назначения",
            "destinationPort": "Порт назначения",
            "trustHostKeyTitle": "Доверять SSH-ключу хоста?",
            "reject": "Отклонить",
            "trust": "Доверять",
            "toggleConnections": "Показать/скрыть подключения",
            "toggleSFTPDrawer": "Показать/скрыть панель SFTP",
            "commandSnippets": "Фрагменты команд",
            "listFiles": "Список файлов",
            "diskUsage": "Использование диска",
            "memoryUsage": "Использование памяти",
            "processMonitor": "Монитор процессов",
            "serverStatus": "Состояние сервера",
            "smallerFont": "Уменьшить шрифт",
            "largerFont": "Увеличить шрифт",
            "fontSize": "Размер шрифта",
            "refresh": "Обновить",
            "connectSFTP": "Подключить SFTP",
            "parentDirectory": "Родительская папка",
            "remotePath": "Удалённый путь",
            "newFolder": "Новая папка",
            "rename": "Переименовать",
            "name": "Имя",
            "open": "Открыть",
            "done": "Готово",
            "failed": "Ошибка",
            "cancelled": "Отменено",
            "queued": "В очереди",
            "running": "Выполняется",
            "retry": "Повторить",
            "renameTab": "Переименовать вкладку",
            "title": "Заголовок",
            "close": "Закрыть",
            "copy": "Копировать",
            "paste": "Вставить",
            "showTermTP": "Показать TermTP",
            "quitTermTP": "Завершить TermTP",
            "view": "Вид",
            "welcomeTitle": "Добро пожаловать",
            "welcomeMessage": "Добро пожаловать в TermTP\n\nВыберите подключение на боковой панели, чтобы начать SSH-сеанс.",
            "connectingTo": "Подключение к",
            "connectedTo": "Подключено к",
            "failedToConnect": "Не удалось подключиться к",
            "noActiveSSHSession": "Нет активного SSH-сеанса",
            "sftpUnsupportedForConnection": "Это подключение не поддерживает управление файлами SFTP",
            "sftpPasswordTitle": "Введите пароль SFTP",
            "sftpPasswordMessage": "Терминал подключён. Введите пароль один раз, чтобы включить управление файлами.",
            "savePassword": "Сохранить пароль",
            "sftpRefreshFailedFormat": "Не удалось обновить удалённые файлы: %@",
            "connectionTimedOutFormat": "Время подключения истекло через %@ секунд"
        ],
        .pt: [
            "terminalTheme": "Tema do terminal",
            "terminalTheme.classicGreen": "Verde clássico",
            "terminalTheme.amber": "Âmbar",
            "terminalTheme.paperWhite": "Branco papel",
            "terminalTheme.ocean": "Oceano",
            "recent": "Recentes",
            "clearHistory": "Limpar histórico",
            "importConnections": "Importar",
            "exportConnections": "Exportar",
            "importConnectionsFailedFormat": "Falha ao importar conexões: %@",
            "exportConnectionsFailedFormat": "Falha ao exportar conexões: %@",
            "loadConnectionsFailedFormat": "Falha ao carregar conexões. A lista atual foi mantida: %@",
            "noConnections": "Sem conexões",
            "addToFavorites": "Adicionar aos favoritos",
            "removeFromFavorites": "Remover dos favoritos",
            "alias": "Apelido",
            "group": "Grupo",
            "host": "Host",
            "port": "Porta",
            "username": "Nome de usuário",
            "tags": "Etiquetas",
            "usePrivateKey": "Usar chave privada",
            "privateKeyPath": "Caminho da chave privada",
            "privateKeyPassphrase": "Frase secreta da chave",
            "password": "Senha",
            "connection": "Conexão",
            "keepConnectionAlive": "Manter conexão ativa",
            "aliveIntervalSeconds": "Intervalo de atividade (s)",
            "aliveMaxCount": "Máximo de atividade",
            "jumpHost": "Servidor de salto",
            "defaultRemotePath": "Caminho remoto padrão",
            "portForwarding": "Encaminhamento de portas",
            "enableForwarding": "Ativar encaminhamento",
            "type": "Tipo",
            "local": "Local",
            "remote": "Remoto",
            "dynamic": "Dinâmico",
            "bindAddress": "Endereço de escuta",
            "destinationHost": "Host de destino",
            "destinationPort": "Porta de destino",
            "trustHostKeyTitle": "Confiar na chave SSH do host?",
            "reject": "Rejeitar",
            "trust": "Confiar",
            "toggleConnections": "Mostrar/Ocultar conexões",
            "toggleSFTPDrawer": "Mostrar/Ocultar painel SFTP",
            "commandSnippets": "Trechos de comando",
            "listFiles": "Listar arquivos",
            "diskUsage": "Uso do disco",
            "memoryUsage": "Uso de memória",
            "processMonitor": "Monitor de processos",
            "serverStatus": "Estado do servidor",
            "smallerFont": "Reduzir fonte",
            "largerFont": "Aumentar fonte",
            "fontSize": "Tamanho da fonte",
            "refresh": "Atualizar",
            "connectSFTP": "Conectar SFTP",
            "parentDirectory": "Pasta superior",
            "remotePath": "Caminho remoto",
            "newFolder": "Nova pasta",
            "rename": "Renomear",
            "name": "Nome",
            "open": "Abrir",
            "done": "Concluído",
            "failed": "Falhou",
            "cancelled": "Cancelado",
            "queued": "Na fila",
            "running": "Em execução",
            "retry": "Tentar novamente",
            "renameTab": "Renomear aba",
            "title": "Título",
            "close": "Fechar",
            "copy": "Copiar",
            "paste": "Colar",
            "showTermTP": "Mostrar TermTP",
            "quitTermTP": "Sair do TermTP",
            "view": "Visualização",
            "welcomeTitle": "Bem-vindo",
            "welcomeMessage": "Bem-vindo ao TermTP\n\nSelecione uma conexão na barra lateral para iniciar uma sessão SSH.",
            "connectingTo": "Conectando a",
            "connectedTo": "Conectado a",
            "failedToConnect": "Falha ao conectar a",
            "noActiveSSHSession": "Nenhuma sessão SSH ativa",
            "sftpUnsupportedForConnection": "Esta conexão não oferece suporte ao gerenciamento de arquivos SFTP",
            "sftpPasswordTitle": "Digite a senha SFTP",
            "sftpPasswordMessage": "O terminal está conectado. Digite a senha uma vez para ativar o gerenciamento de arquivos.",
            "savePassword": "Salvar senha",
            "sftpRefreshFailedFormat": "Falha ao atualizar arquivos remotos: %@",
            "connectionTimedOutFormat": "A conexão expirou após %@ segundos"
        ]
    ]
}
