import Foundation

extension AppStrings {
    static let values: [AppLanguage: [String: String]] = [
        .zhHans: [
            "settings": "设置",
            "language": "语言",
            "terminalTheme": "终端主题",
            "security": "安全",
            "trustedHostKeys": "已信任主机密钥",
            "noTrustedHostKeys": "暂无已信任主机",
            "clearTrustedHostKeys": "清空主机密钥",
            "terminalTheme.classicGreen": "经典黑绿",
            "terminalTheme.amber": "琥珀",
            "terminalTheme.paperWhite": "纸白",
            "terminalTheme.ocean": "海洋",
            "newConnection": "新建连接",
            "cancel": "取消",
            "ok": "确定",
            "connect": "连接",
            "connections": "连接",
            "search": "搜索",
            "recent": "最近",
            "favorites": "收藏",
            "history": "历史",
            "clearHistory": "清空历史",
            "importConnections": "导入",
            "exportConnections": "导出",
            "importConnectionsFailedFormat": "导入连接失败：%@",
            "exportConnectionsFailedFormat": "导出连接失败：%@",
            "noConnections": "暂无连接",
            "addToFavorites": "加入收藏",
            "removeFromFavorites": "取消收藏",
            "delete": "删除",
            "alias": "别名",
            "group": "分组",
            "host": "主机",
            "port": "端口",
            "username": "用户名",
            "tags": "标签",
            "usePrivateKey": "使用私钥",
            "privateKeyPath": "私钥路径",
            "privateKeyPassphrase": "私钥密码",
            "password": "密码",
            "connection": "连接",
            "keepConnectionAlive": "保持连接",
            "aliveIntervalSeconds": "保活间隔秒数",
            "aliveMaxCount": "保活最大次数",
            "jumpHost": "跳板机",
            "defaultRemotePath": "默认远程目录",
            "portForwarding": "端口转发",
            "enableForwarding": "启用转发",
            "type": "类型",
            "local": "本地",
            "remote": "远程",
            "dynamic": "动态",
            "bindAddress": "绑定地址",
            "destinationHost": "目标主机",
            "destinationPort": "目标端口",
            "trustHostKeyTitle": "信任 SSH 主机密钥？",
            "reject": "拒绝",
            "trust": "信任",
            "toggleConnections": "显示/隐藏连接栏",
            "toggleSFTPDrawer": "显示/隐藏 SFTP 面板",
            "commandSnippets": "命令片段",
            "listFiles": "列出文件",
            "diskUsage": "磁盘使用",
            "memoryUsage": "内存使用",
            "processMonitor": "进程监控",
            "serverStatus": "服务器状态",
            "smallerFont": "减小字体",
            "largerFont": "增大字体",
            "fontSize": "字体大小",
            "refresh": "刷新",
            "parentDirectory": "上级目录",
            "remotePath": "远程路径",
            "uploadHere": "上传到这里",
            "newFolder": "新建文件夹",
            "rename": "重命名",
            "name": "名称",
            "open": "打开",
            "download": "下载",
            "preview": "预览",
            "changePermissions": "修改权限",
            "permissions": "权限",
            "invalidPermissions": "权限格式无效，请输入 644 或 755 这样的八进制数字",
            "previewFailedFormat": "预览失败：%@",
            "permissionsChangeFailedFormat": "修改权限失败：%@",
            "choosePrivateKey": "选择私钥",
            "done": "完成",
            "failed": "失败",
            "cancelled": "已取消",
            "queued": "排队中",
            "running": "传输中",
            "retry": "重试",
            "transfers": "传输",
            "clearFinishedTransfers": "清理已完成",
            "secondsRemainingFormat": "剩余 %d 秒",
            "minutesSecondsRemainingFormat": "剩余 %d:%02d",
            "renameTab": "重命名标签页",
            "title": "标题",
            "close": "关闭",
            "copy": "复制",
            "paste": "粘贴",
            "confirmMultilinePasteTitle": "粘贴多行命令？",
            "confirmMultilinePasteMessage": "剪贴板包含多行内容，粘贴后可能立即执行多条命令。",
            "showTermTP": "显示 TermTP",
            "quitTermTP": "退出 TermTP",
            "view": "视图",
            "welcomeTitle": "欢迎",
            "welcomeMessage": "欢迎使用 TermTP\n\n从连接栏选择主机开始 SSH 会话。",
            "connectingTo": "正在连接",
            "connectedTo": "已连接到",
            "failedToConnect": "连接失败",
            "noActiveSSHSession": "没有可用的 SSH 会话",
            "sftpUnsupportedForConnection": "当前连接暂不支持 SFTP 文件管理",
            "sftpPasswordTitle": "输入 SFTP 密码",
            "sftpPasswordMessage": "终端已连接。请输入一次密码，用于打开下方文件管理。",
            "sftpRefreshFailedFormat": "刷新远程文件失败：%@",
            "connectionTimedOutFormat": "连接超时，已等待 %@ 秒"
        ],
        .en: [
            "settings": "Settings",
            "language": "Language",
            "terminalTheme": "Terminal Theme",
            "security": "Security",
            "trustedHostKeys": "Trusted Host Keys",
            "noTrustedHostKeys": "No trusted hosts",
            "clearTrustedHostKeys": "Clear Host Keys",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "newConnection": "New Connection",
            "cancel": "Cancel",
            "ok": "OK",
            "connect": "Connect",
            "connections": "Connections",
            "search": "Search",
            "recent": "Recent",
            "favorites": "Favorites",
            "history": "History",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "delete": "Delete",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "uploadHere": "Upload Here",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "download": "Download",
            "preview": "Preview",
            "changePermissions": "Change Permissions",
            "permissions": "Permissions",
            "invalidPermissions": "Invalid permissions. Use an octal value like 644 or 755.",
            "previewFailedFormat": "Preview failed: %@",
            "permissionsChangeFailedFormat": "Failed to change permissions: %@",
            "choosePrivateKey": "Choose Private Key",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transfers",
            "clearFinishedTransfers": "Clear finished",
            "secondsRemainingFormat": "%d s left",
            "minutesSecondsRemainingFormat": "%d:%02d left",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Paste multiple lines?",
            "confirmMultilinePasteMessage": "The clipboard contains multiple lines and may run several commands immediately.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpPasswordTitle": "Enter SFTP Password",
            "sftpPasswordMessage": "The terminal is connected. Enter the password once to enable file management below.",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .ja: [
            "settings": "設定",
            "language": "言語",
            "security": "セキュリティ",
            "trustedHostKeys": "信頼済みホスト鍵",
            "noTrustedHostKeys": "信頼済みホストなし",
            "clearTrustedHostKeys": "ホスト鍵を消去",
            "newConnection": "新規接続",
            "cancel": "キャンセル",
            "ok": "OK",
            "connect": "接続",
            "connections": "接続",
            "search": "検索",
            "favorites": "お気に入り",
            "history": "履歴",
            "delete": "削除",
            "download": "ダウンロード",
            "uploadHere": "ここにアップロード",
            "preview": "プレビュー",
            "changePermissions": "権限を変更",
            "permissions": "権限",
            "invalidPermissions": "権限形式が無効です。644 や 755 のように入力してください。",
            "previewFailedFormat": "プレビュー失敗: %@",
            "permissionsChangeFailedFormat": "権限変更失敗: %@",
            "choosePrivateKey": "秘密鍵を選択",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "転送",
            "clearFinishedTransfers": "完了を消去",
            "secondsRemainingFormat": "残り %d 秒",
            "minutesSecondsRemainingFormat": "残り %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "複数行を貼り付けますか？",
            "confirmMultilinePasteMessage": "クリップボードに複数行が含まれ、複数のコマンドがすぐ実行される可能性があります。",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .ko: [
            "settings": "설정",
            "language": "언어",
            "security": "보안",
            "trustedHostKeys": "신뢰한 호스트 키",
            "noTrustedHostKeys": "신뢰한 호스트 없음",
            "clearTrustedHostKeys": "호스트 키 지우기",
            "newConnection": "새 연결",
            "cancel": "취소",
            "ok": "확인",
            "connect": "연결",
            "connections": "연결",
            "search": "검색",
            "favorites": "즐겨찾기",
            "history": "기록",
            "delete": "삭제",
            "download": "다운로드",
            "uploadHere": "여기에 업로드",
            "preview": "미리보기",
            "changePermissions": "권한 변경",
            "permissions": "권한",
            "invalidPermissions": "권한 형식이 잘못되었습니다. 644 또는 755처럼 입력하세요.",
            "previewFailedFormat": "미리보기 실패: %@",
            "permissionsChangeFailedFormat": "권한 변경 실패: %@",
            "choosePrivateKey": "개인 키 선택",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "전송",
            "clearFinishedTransfers": "완료 항목 지우기",
            "secondsRemainingFormat": "%d초 남음",
            "minutesSecondsRemainingFormat": "%d:%02d 남음",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "여러 줄을 붙여넣을까요?",
            "confirmMultilinePasteMessage": "클립보드에 여러 줄이 있어 여러 명령이 즉시 실행될 수 있습니다.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .es: [
            "settings": "Configuración",
            "language": "Idioma",
            "security": "Seguridad",
            "trustedHostKeys": "Claves de host confiables",
            "noTrustedHostKeys": "Sin hosts confiables",
            "clearTrustedHostKeys": "Borrar claves de host",
            "newConnection": "Nueva conexión",
            "cancel": "Cancelar",
            "ok": "Aceptar",
            "connect": "Conectar",
            "connections": "Conexiones",
            "search": "Buscar",
            "favorites": "Favoritos",
            "history": "Historial",
            "delete": "Eliminar",
            "download": "Descargar",
            "uploadHere": "Subir aquí",
            "preview": "Vista previa",
            "changePermissions": "Cambiar permisos",
            "permissions": "Permisos",
            "invalidPermissions": "Permisos no válidos. Usa un valor octal como 644 o 755.",
            "previewFailedFormat": "Error de vista previa: %@",
            "permissionsChangeFailedFormat": "No se pudieron cambiar los permisos: %@",
            "choosePrivateKey": "Elegir clave privada",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transferencias",
            "clearFinishedTransfers": "Limpiar terminadas",
            "secondsRemainingFormat": "Quedan %d s",
            "minutesSecondsRemainingFormat": "Quedan %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "¿Pegar varias líneas?",
            "confirmMultilinePasteMessage": "El portapapeles contiene varias líneas y puede ejecutar varios comandos de inmediato.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .fr: [
            "settings": "Réglages",
            "language": "Langue",
            "security": "Sécurité",
            "trustedHostKeys": "Clés d’hôte approuvées",
            "noTrustedHostKeys": "Aucun hôte approuvé",
            "clearTrustedHostKeys": "Effacer les clés d’hôte",
            "newConnection": "Nouvelle connexion",
            "cancel": "Annuler",
            "ok": "OK",
            "connect": "Connexion",
            "connections": "Connexions",
            "search": "Rechercher",
            "favorites": "Favoris",
            "history": "Historique",
            "delete": "Supprimer",
            "download": "Télécharger",
            "uploadHere": "Téléverser ici",
            "preview": "Aperçu",
            "changePermissions": "Modifier les permissions",
            "permissions": "Permissions",
            "invalidPermissions": "Permissions invalides. Utilisez une valeur octale comme 644 ou 755.",
            "previewFailedFormat": "Échec de l’aperçu : %@",
            "permissionsChangeFailedFormat": "Échec du changement de permissions : %@",
            "choosePrivateKey": "Choisir une clé privée",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transferts",
            "clearFinishedTransfers": "Effacer terminés",
            "secondsRemainingFormat": "%d s restantes",
            "minutesSecondsRemainingFormat": "%d:%02d restantes",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Coller plusieurs lignes ?",
            "confirmMultilinePasteMessage": "Le presse-papiers contient plusieurs lignes et peut exécuter plusieurs commandes immédiatement.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .de: [
            "settings": "Einstellungen",
            "language": "Sprache",
            "security": "Sicherheit",
            "trustedHostKeys": "Vertrauenswürdige Hostschlüssel",
            "noTrustedHostKeys": "Keine vertrauenswürdigen Hosts",
            "clearTrustedHostKeys": "Hostschlüssel löschen",
            "newConnection": "Neue Verbindung",
            "cancel": "Abbrechen",
            "ok": "OK",
            "connect": "Verbinden",
            "connections": "Verbindungen",
            "search": "Suchen",
            "favorites": "Favoriten",
            "history": "Verlauf",
            "delete": "Löschen",
            "download": "Herunterladen",
            "uploadHere": "Hier hochladen",
            "preview": "Vorschau",
            "changePermissions": "Berechtigungen ändern",
            "permissions": "Berechtigungen",
            "invalidPermissions": "Ungültige Berechtigungen. Verwende einen Oktalwert wie 644 oder 755.",
            "previewFailedFormat": "Vorschau fehlgeschlagen: %@",
            "permissionsChangeFailedFormat": "Berechtigungen konnten nicht geändert werden: %@",
            "choosePrivateKey": "Privaten Schlüssel wählen",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Übertragungen",
            "clearFinishedTransfers": "Fertige löschen",
            "secondsRemainingFormat": "%d s übrig",
            "minutesSecondsRemainingFormat": "%d:%02d übrig",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Mehrere Zeilen einfügen?",
            "confirmMultilinePasteMessage": "Die Zwischenablage enthält mehrere Zeilen und kann sofort mehrere Befehle ausführen.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .ru: [
            "settings": "Настройки",
            "language": "Язык",
            "security": "Безопасность",
            "trustedHostKeys": "Доверенные ключи хостов",
            "noTrustedHostKeys": "Нет доверенных хостов",
            "clearTrustedHostKeys": "Очистить ключи хостов",
            "newConnection": "Новое подключение",
            "cancel": "Отмена",
            "ok": "OK",
            "connect": "Подключить",
            "connections": "Подключения",
            "search": "Поиск",
            "favorites": "Избранное",
            "history": "История",
            "delete": "Удалить",
            "download": "Скачать",
            "uploadHere": "Загрузить сюда",
            "preview": "Просмотр",
            "changePermissions": "Изменить права",
            "permissions": "Права",
            "invalidPermissions": "Неверный формат прав. Используйте восьмеричное значение, например 644 или 755.",
            "previewFailedFormat": "Ошибка просмотра: %@",
            "permissionsChangeFailedFormat": "Не удалось изменить права: %@",
            "choosePrivateKey": "Выбрать приватный ключ",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Передачи",
            "clearFinishedTransfers": "Очистить завершённые",
            "secondsRemainingFormat": "Осталось %d с",
            "minutesSecondsRemainingFormat": "Осталось %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Вставить несколько строк?",
            "confirmMultilinePasteMessage": "Буфер обмена содержит несколько строк и может сразу выполнить несколько команд.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .pt: [
            "settings": "Definições",
            "language": "Idioma",
            "security": "Segurança",
            "trustedHostKeys": "Chaves de host confiáveis",
            "noTrustedHostKeys": "Nenhum host confiável",
            "clearTrustedHostKeys": "Limpar chaves de host",
            "newConnection": "Nova conexão",
            "cancel": "Cancelar",
            "ok": "OK",
            "connect": "Conectar",
            "connections": "Conexões",
            "search": "Pesquisar",
            "favorites": "Favoritos",
            "history": "Histórico",
            "delete": "Excluir",
            "download": "Baixar",
            "uploadHere": "Enviar aqui",
            "preview": "Pré-visualizar",
            "changePermissions": "Alterar permissões",
            "permissions": "Permissões",
            "invalidPermissions": "Permissões inválidas. Use um valor octal como 644 ou 755.",
            "previewFailedFormat": "Falha na pré-visualização: %@",
            "permissionsChangeFailedFormat": "Falha ao alterar permissões: %@",
            "choosePrivateKey": "Escolher chave privada",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transferências",
            "clearFinishedTransfers": "Limpar concluídas",
            "secondsRemainingFormat": "Restam %d s",
            "minutesSecondsRemainingFormat": "Restam %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Colar várias linhas?",
            "confirmMultilinePasteMessage": "A área de transferência contém várias linhas e pode executar vários comandos imediatamente.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ]
    ]
}
