import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case zhHans = "zh-Hans"
    case en
    case ja
    case ko
    case es
    case fr
    case de
    case ru
    case pt

    static let `default`: AppLanguage = .zhHans

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .zhHans: return "中文"
        case .en: return "English"
        case .ja: return "日本語"
        case .ko: return "한국어"
        case .es: return "Español"
        case .fr: return "Français"
        case .de: return "Deutsch"
        case .ru: return "Русский"
        case .pt: return "Português"
        }
    }
}

struct AppStrings: Equatable, Sendable {
    let currentLanguage: AppLanguage

    init(language: AppLanguage) {
        self.currentLanguage = language
    }

    private var dictionary: [String: String] {
        var values = Self.values[.en] ?? [:]
        values.merge(Self.resolvedValues(for: currentLanguage)) { _, new in new }
        return values
    }

    subscript(_ key: String) -> String {
        dictionary[key] ?? Self.values[.en]?[key] ?? key
    }

    var settings: String { self["settings"] }
    var language: String { self["language"] }
    var terminalTheme: String { self["terminalTheme"] }
    var security: String { self["security"] }
    var trustedHostKeys: String { self["trustedHostKeys"] }
    var noTrustedHostKeys: String { self["noTrustedHostKeys"] }
    var clearTrustedHostKeys: String { self["clearTrustedHostKeys"] }
    func terminalThemeName(_ theme: TerminalTheme) -> String {
        self["terminalTheme.\(theme.rawValue)"]
    }
    var newConnection: String { self["newConnection"] }
    var cancel: String { self["cancel"] }
    var ok: String { self["ok"] }
    var connect: String { self["connect"] }
    var connections: String { self["connections"] }
    var search: String { self["search"] }
    var recent: String { self["recent"] }
    var favorites: String { self["favorites"] }
    var history: String { self["history"] }
    var clearHistory: String { self["clearHistory"] }
    var importConnections: String { self["importConnections"] }
    var exportConnections: String { self["exportConnections"] }
    func importConnectionsFailed(_ message: String) -> String {
        String(format: self["importConnectionsFailedFormat"], message)
    }
    func exportConnectionsFailed(_ message: String) -> String {
        String(format: self["exportConnectionsFailedFormat"], message)
    }
    var noConnections: String { self["noConnections"] }
    var addToFavorites: String { self["addToFavorites"] }
    var removeFromFavorites: String { self["removeFromFavorites"] }
    var delete: String { self["delete"] }
    var alias: String { self["alias"] }
    var group: String { self["group"] }
    var host: String { self["host"] }
    var port: String { self["port"] }
    var username: String { self["username"] }
    var tags: String { self["tags"] }
    var usePrivateKey: String { self["usePrivateKey"] }
    var privateKeyPath: String { self["privateKeyPath"] }
    var privateKeyPassphrase: String { self["privateKeyPassphrase"] }
    var password: String { self["password"] }
    var connection: String { self["connection"] }
    var keepConnectionAlive: String { self["keepConnectionAlive"] }
    var aliveIntervalSeconds: String { self["aliveIntervalSeconds"] }
    var aliveMaxCount: String { self["aliveMaxCount"] }
    var jumpHost: String { self["jumpHost"] }
    var defaultRemotePath: String { self["defaultRemotePath"] }
    var portForwarding: String { self["portForwarding"] }
    var enableForwarding: String { self["enableForwarding"] }
    var type: String { self["type"] }
    var local: String { self["local"] }
    var remote: String { self["remote"] }
    var dynamic: String { self["dynamic"] }
    var bindAddress: String { self["bindAddress"] }
    var destinationHost: String { self["destinationHost"] }
    var destinationPort: String { self["destinationPort"] }
    var trustHostKeyTitle: String { self["trustHostKeyTitle"] }
    var reject: String { self["reject"] }
    var trust: String { self["trust"] }
    var toggleConnections: String { self["toggleConnections"] }
    var toggleSFTPDrawer: String { self["toggleSFTPDrawer"] }
    var commandSnippets: String { self["commandSnippets"] }
    var listFiles: String { self["listFiles"] }
    var diskUsage: String { self["diskUsage"] }
    var memoryUsage: String { self["memoryUsage"] }
    var processMonitor: String { self["processMonitor"] }
    var serverStatus: String { self["serverStatus"] }
    var smallerFont: String { self["smallerFont"] }
    var largerFont: String { self["largerFont"] }
    var fontSize: String { self["fontSize"] }
    var refresh: String { self["refresh"] }
    var parentDirectory: String { self["parentDirectory"] }
    var remotePath: String { self["remotePath"] }
    var uploadHere: String { self["uploadHere"] }
    var newFolder: String { self["newFolder"] }
    var rename: String { self["rename"] }
    var name: String { self["name"] }
    var open: String { self["open"] }
    var download: String { self["download"] }
    var preview: String { self["preview"] }
    var changePermissions: String { self["changePermissions"] }
    var permissions: String { self["permissions"] }
    var invalidPermissions: String { self["invalidPermissions"] }
    func previewFailed(_ message: String) -> String {
        String(format: self["previewFailedFormat"], message)
    }
    func permissionsChangeFailed(_ message: String) -> String {
        String(format: self["permissionsChangeFailedFormat"], message)
    }
    var choosePrivateKey: String { self["choosePrivateKey"] }
    var done: String { self["done"] }
    var failed: String { self["failed"] }
    var cancelled: String { self["cancelled"] }
    var queued: String { self["queued"] }
    var running: String { self["running"] }
    var retry: String { self["retry"] }
    var transfers: String { self["transfers"] }
    var clearFinishedTransfers: String { self["clearFinishedTransfers"] }
    func secondsRemaining(_ seconds: Int) -> String {
        String(format: self["secondsRemainingFormat"], seconds)
    }
    func minutesSecondsRemaining(_ minutes: Int, _ seconds: Int) -> String {
        String(format: self["minutesSecondsRemainingFormat"], minutes, seconds)
    }
    var renameTab: String { self["renameTab"] }
    var title: String { self["title"] }
    var close: String { self["close"] }
    var copy: String { self["copy"] }
    var paste: String { self["paste"] }
    var confirmMultilinePasteTitle: String { self["confirmMultilinePasteTitle"] }
    var confirmMultilinePasteMessage: String { self["confirmMultilinePasteMessage"] }
    var showTermTP: String { self["showTermTP"] }
    var quitTermTP: String { self["quitTermTP"] }
    var view: String { self["view"] }
    var welcomeTitle: String { self["welcomeTitle"] }
    var welcomeMessage: String { self["welcomeMessage"] }
    var connectingTo: String { self["connectingTo"] }
    var connectedTo: String { self["connectedTo"] }
    var failedToConnect: String { self["failedToConnect"] }
    var noActiveSSHSession: String { self["noActiveSSHSession"] }
    var sftpUnsupportedForConnection: String { self["sftpUnsupportedForConnection"] }
    func sftpRefreshFailed(_ message: String) -> String {
        String(format: self["sftpRefreshFailedFormat"], message)
    }
    func connectionTimedOut(seconds: Double) -> String {
        String(format: self["connectionTimedOutFormat"], "\(seconds)")
    }

    static var requiredKeys: Set<String> {
        Set(values[.en]?.keys ?? [:].keys)
    }

    static var commonInterfaceKeys: Set<String> {
        [
            "terminalTheme", "recent", "clearHistory", "importConnections", "exportConnections",
            "noConnections", "addToFavorites", "removeFromFavorites", "alias", "username",
            "usePrivateKey", "privateKeyPath", "password", "keepConnectionAlive", "jumpHost",
            "portForwarding", "trustHostKeyTitle", "toggleConnections", "commandSnippets",
            "listFiles", "diskUsage", "memoryUsage", "serverStatus", "fontSize", "refresh",
            "parentDirectory", "remotePath", "newFolder", "renameTab", "copy", "paste",
            "showTermTP", "quitTermTP", "welcomeTitle", "connectingTo", "connectedTo",
            "failedToConnect", "noActiveSSHSession"
        ]
    }

    static func keys(for language: AppLanguage) -> Set<String> {
        Set(resolvedValues(for: language).keys)
    }

    static func rawValue(for key: String, language: AppLanguage) -> String {
        resolvedValues(for: language)[key] ?? ""
    }

    private static func resolvedValues(for language: AppLanguage) -> [String: String] {
        var values = Self.values[language] ?? [:]
        values.merge(Self.supplementalLocalizedValues[language] ?? [:]) { _, new in new }
        return values
    }

    static let supplementalLocalizedValues: [AppLanguage: [String: String]] = [
        .ja: [
            "terminalTheme": "ターミナルテーマ",
            "terminalTheme.classicGreen": "クラシックグリーン",
            "terminalTheme.amber": "アンバー",
            "terminalTheme.paperWhite": "ペーパーホワイト",
            "terminalTheme.ocean": "オーシャン",
            "recent": "最近",
            "clearHistory": "履歴を消去",
            "importConnections": "インポート",
            "exportConnections": "エクスポート",
            "importConnectionsFailedFormat": "接続のインポートに失敗しました: %@",
            "exportConnectionsFailedFormat": "接続のエクスポートに失敗しました: %@",
            "noConnections": "接続なし",
            "addToFavorites": "お気に入りに追加",
            "removeFromFavorites": "お気に入りから削除",
            "alias": "別名",
            "group": "グループ",
            "host": "ホスト",
            "port": "ポート",
            "username": "ユーザー名",
            "tags": "タグ",
            "usePrivateKey": "秘密鍵を使用",
            "privateKeyPath": "秘密鍵のパス",
            "privateKeyPassphrase": "秘密鍵のパスフレーズ",
            "password": "パスワード",
            "connection": "接続",
            "keepConnectionAlive": "接続を維持",
            "aliveIntervalSeconds": "キープアライブ間隔（秒）",
            "aliveMaxCount": "キープアライブ最大回数",
            "jumpHost": "ジャンプホスト",
            "defaultRemotePath": "デフォルトのリモートパス",
            "portForwarding": "ポート転送",
            "enableForwarding": "転送を有効化",
            "type": "種類",
            "local": "ローカル",
            "remote": "リモート",
            "dynamic": "ダイナミック",
            "bindAddress": "バインドアドレス",
            "destinationHost": "宛先ホスト",
            "destinationPort": "宛先ポート",
            "trustHostKeyTitle": "SSH ホスト鍵を信頼しますか？",
            "reject": "拒否",
            "trust": "信頼",
            "toggleConnections": "接続パネルを切り替え",
            "toggleSFTPDrawer": "SFTP パネルを切り替え",
            "commandSnippets": "コマンドスニペット",
            "listFiles": "ファイル一覧",
            "diskUsage": "ディスク使用量",
            "memoryUsage": "メモリ使用量",
            "processMonitor": "プロセスモニター",
            "serverStatus": "サーバー状態",
            "smallerFont": "フォントを小さく",
            "largerFont": "フォントを大きく",
            "fontSize": "フォントサイズ",
            "refresh": "更新",
            "parentDirectory": "親ディレクトリ",
            "remotePath": "リモートパス",
            "newFolder": "新規フォルダ",
            "rename": "名前変更",
            "name": "名前",
            "open": "開く",
            "done": "完了",
            "failed": "失敗",
            "cancelled": "キャンセル済み",
            "queued": "待機中",
            "running": "実行中",
            "retry": "再試行",
            "renameTab": "タブ名を変更",
            "title": "タイトル",
            "close": "閉じる",
            "copy": "コピー",
            "paste": "貼り付け",
            "showTermTP": "TermTP を表示",
            "quitTermTP": "TermTP を終了",
            "view": "表示",
            "welcomeTitle": "ようこそ",
            "welcomeMessage": "TermTP へようこそ\n\nサイドバーから接続を選んで SSH セッションを開始してください。",
            "connectingTo": "接続中",
            "connectedTo": "接続しました",
            "failedToConnect": "接続に失敗しました",
            "noActiveSSHSession": "有効な SSH セッションがありません",
            "sftpUnsupportedForConnection": "この接続では SFTP ファイル管理を使用できません",
            "sftpRefreshFailedFormat": "リモートファイルの更新に失敗しました: %@",
            "connectionTimedOutFormat": "接続が %@ 秒でタイムアウトしました"
        ],
        .ko: [
            "terminalTheme": "터미널 테마",
            "terminalTheme.classicGreen": "클래식 그린",
            "terminalTheme.amber": "앰버",
            "terminalTheme.paperWhite": "페이퍼 화이트",
            "terminalTheme.ocean": "오션",
            "recent": "최근",
            "clearHistory": "기록 지우기",
            "importConnections": "가져오기",
            "exportConnections": "내보내기",
            "importConnectionsFailedFormat": "연결 가져오기 실패: %@",
            "exportConnectionsFailedFormat": "연결 내보내기 실패: %@",
            "noConnections": "연결 없음",
            "addToFavorites": "즐겨찾기에 추가",
            "removeFromFavorites": "즐겨찾기에서 제거",
            "alias": "별칭",
            "group": "그룹",
            "host": "호스트",
            "port": "포트",
            "username": "사용자 이름",
            "tags": "태그",
            "usePrivateKey": "개인 키 사용",
            "privateKeyPath": "개인 키 경로",
            "privateKeyPassphrase": "개인 키 암호",
            "password": "비밀번호",
            "connection": "연결",
            "keepConnectionAlive": "연결 유지",
            "aliveIntervalSeconds": "유지 간격(초)",
            "aliveMaxCount": "연결 유지 최대 횟수",
            "jumpHost": "점프 호스트",
            "defaultRemotePath": "기본 원격 경로",
            "portForwarding": "포트 포워딩",
            "enableForwarding": "전달 활성화",
            "type": "유형",
            "local": "로컬",
            "remote": "원격",
            "dynamic": "동적",
            "bindAddress": "바인드 주소",
            "destinationHost": "대상 호스트",
            "destinationPort": "대상 포트",
            "trustHostKeyTitle": "SSH 호스트 키를 신뢰할까요?",
            "reject": "거부",
            "trust": "신뢰",
            "toggleConnections": "연결 패널 전환",
            "toggleSFTPDrawer": "SFTP 패널 전환",
            "commandSnippets": "명령 스니펫",
            "listFiles": "파일 목록",
            "diskUsage": "디스크 사용량",
            "memoryUsage": "메모리 사용량",
            "processMonitor": "프로세스 모니터",
            "serverStatus": "서버 상태",
            "smallerFont": "글꼴 작게",
            "largerFont": "글꼴 크게",
            "fontSize": "글꼴 크기",
            "refresh": "새로고침",
            "parentDirectory": "상위 폴더",
            "remotePath": "원격 경로",
            "newFolder": "새 폴더",
            "rename": "이름 변경",
            "name": "이름",
            "open": "열기",
            "done": "완료",
            "failed": "실패",
            "cancelled": "취소됨",
            "queued": "대기 중",
            "running": "실행 중",
            "retry": "다시 시도",
            "renameTab": "탭 이름 변경",
            "title": "제목",
            "close": "닫기",
            "copy": "복사",
            "paste": "붙여넣기",
            "showTermTP": "TermTP 보기",
            "quitTermTP": "TermTP 종료",
            "view": "보기",
            "welcomeTitle": "환영합니다",
            "welcomeMessage": "TermTP에 오신 것을 환영합니다\n\n사이드바에서 연결을 선택해 SSH 세션을 시작하세요.",
            "connectingTo": "연결 중",
            "connectedTo": "연결됨",
            "failedToConnect": "연결 실패",
            "noActiveSSHSession": "활성 SSH 세션이 없습니다",
            "sftpUnsupportedForConnection": "이 연결은 SFTP 파일 관리를 지원하지 않습니다",
            "sftpRefreshFailedFormat": "원격 파일 새로고침 실패: %@",
            "connectionTimedOutFormat": "%@초 후 연결 시간이 초과되었습니다"
        ],
        .es: [
            "terminalTheme": "Tema del terminal",
            "terminalTheme.classicGreen": "Verde clásico",
            "terminalTheme.amber": "Ámbar",
            "terminalTheme.paperWhite": "Blanco papel",
            "terminalTheme.ocean": "Océano",
            "recent": "Recientes",
            "clearHistory": "Borrar historial",
            "importConnections": "Importar",
            "exportConnections": "Exportar",
            "importConnectionsFailedFormat": "No se pudieron importar las conexiones: %@",
            "exportConnectionsFailedFormat": "No se pudieron exportar las conexiones: %@",
            "noConnections": "Sin conexiones",
            "addToFavorites": "Añadir a favoritos",
            "removeFromFavorites": "Quitar de favoritos",
            "alias": "Nombre corto",
            "group": "Grupo",
            "host": "Servidor",
            "port": "Puerto",
            "username": "Usuario",
            "tags": "Etiquetas",
            "usePrivateKey": "Usar clave privada",
            "privateKeyPath": "Ruta de clave privada",
            "privateKeyPassphrase": "Frase de clave privada",
            "password": "Contraseña",
            "connection": "Conexión",
            "keepConnectionAlive": "Mantener conexión activa",
            "aliveIntervalSeconds": "Intervalo de actividad (s)",
            "aliveMaxCount": "Reintentos de keepalive",
            "jumpHost": "Servidor de salto",
            "defaultRemotePath": "Ruta remota predeterminada",
            "portForwarding": "Reenvío de puertos",
            "enableForwarding": "Activar reenvío",
            "type": "Tipo",
            "dynamic": "Dinámico",
            "bindAddress": "Dirección de escucha",
            "destinationHost": "Host de destino",
            "destinationPort": "Puerto de destino",
            "trustHostKeyTitle": "¿Confiar en la clave SSH del host?",
            "reject": "Rechazar",
            "trust": "Confiar",
            "toggleConnections": "Mostrar/Ocultar conexiones",
            "toggleSFTPDrawer": "Mostrar/Ocultar panel SFTP",
            "commandSnippets": "Fragmentos de comandos",
            "listFiles": "Listar archivos",
            "diskUsage": "Uso de disco",
            "memoryUsage": "Uso de memoria",
            "processMonitor": "Monitor de procesos",
            "serverStatus": "Estado del servidor",
            "smallerFont": "Reducir fuente",
            "largerFont": "Aumentar fuente",
            "fontSize": "Tamaño de fuente",
            "refresh": "Actualizar",
            "parentDirectory": "Carpeta superior",
            "remotePath": "Ruta remota",
            "newFolder": "Nueva carpeta",
            "rename": "Renombrar",
            "name": "Nombre",
            "open": "Abrir",
            "done": "Completado",
            "failed": "Fallido",
            "cancelled": "Cancelado",
            "queued": "En cola",
            "running": "En curso",
            "retry": "Reintentar",
            "renameTab": "Renombrar pestaña",
            "title": "Título",
            "close": "Cerrar",
            "copy": "Copiar",
            "paste": "Pegar",
            "showTermTP": "Mostrar TermTP",
            "quitTermTP": "Salir de TermTP",
            "view": "Vista",
            "welcomeTitle": "Bienvenido",
            "welcomeMessage": "Bienvenido a TermTP\n\nSelecciona una conexión en la barra lateral para iniciar una sesión SSH.",
            "connectingTo": "Conectando a",
            "connectedTo": "Conectado a",
            "failedToConnect": "No se pudo conectar a",
            "noActiveSSHSession": "No hay sesión SSH activa",
            "sftpUnsupportedForConnection": "Esta conexión no admite gestión de archivos SFTP",
            "sftpRefreshFailedFormat": "No se pudieron actualizar los archivos remotos: %@",
            "connectionTimedOutFormat": "La conexión agotó el tiempo tras %@ segundos"
        ],
        .fr: [
            "terminalTheme": "Thème du terminal",
            "terminalTheme.classicGreen": "Vert classique",
            "terminalTheme.amber": "Ambre",
            "terminalTheme.paperWhite": "Blanc papier",
            "terminalTheme.ocean": "Océan",
            "recent": "Récents",
            "clearHistory": "Effacer l’historique",
            "importConnections": "Importer",
            "exportConnections": "Exporter",
            "importConnectionsFailedFormat": "Échec de l’import des connexions : %@",
            "exportConnectionsFailedFormat": "Échec de l’export des connexions : %@",
            "noConnections": "Aucune connexion",
            "addToFavorites": "Ajouter aux favoris",
            "removeFromFavorites": "Retirer des favoris",
            "alias": "Nom court",
            "group": "Groupe",
            "host": "Hôte",
            "port": "Port",
            "username": "Nom d’utilisateur",
            "tags": "Étiquettes",
            "usePrivateKey": "Utiliser une clé privée",
            "privateKeyPath": "Chemin de la clé privée",
            "privateKeyPassphrase": "Phrase secrète de la clé",
            "password": "Mot de passe",
            "connection": "Connexion",
            "keepConnectionAlive": "Garder la connexion active",
            "aliveIntervalSeconds": "Intervalle keepalive (s)",
            "aliveMaxCount": "Nombre maximal de keepalive",
            "jumpHost": "Hôte bastion",
            "defaultRemotePath": "Chemin distant par défaut",
            "portForwarding": "Redirection de ports",
            "enableForwarding": "Activer la redirection",
            "type": "Type",
            "local": "Local",
            "remote": "Distant",
            "dynamic": "Dynamique",
            "bindAddress": "Adresse d’écoute",
            "destinationHost": "Hôte de destination",
            "destinationPort": "Port de destination",
            "trustHostKeyTitle": "Faire confiance à la clé SSH de l’hôte ?",
            "reject": "Refuser",
            "trust": "Faire confiance",
            "toggleConnections": "Afficher/Masquer les connexions",
            "toggleSFTPDrawer": "Afficher/Masquer le panneau SFTP",
            "commandSnippets": "Extraits de commandes",
            "listFiles": "Lister les fichiers",
            "diskUsage": "Utilisation du disque",
            "memoryUsage": "Utilisation mémoire",
            "processMonitor": "Moniteur de processus",
            "serverStatus": "État du serveur",
            "smallerFont": "Réduire la police",
            "largerFont": "Agrandir la police",
            "fontSize": "Taille de police",
            "refresh": "Actualiser",
            "parentDirectory": "Dossier parent",
            "remotePath": "Chemin distant",
            "newFolder": "Nouveau dossier",
            "rename": "Renommer",
            "name": "Nom",
            "open": "Ouvrir",
            "done": "Terminé",
            "failed": "Échec",
            "cancelled": "Annulé",
            "queued": "En file",
            "running": "En cours",
            "retry": "Réessayer",
            "renameTab": "Renommer l’onglet",
            "title": "Titre",
            "close": "Fermer",
            "copy": "Copier",
            "paste": "Coller",
            "showTermTP": "Afficher TermTP",
            "quitTermTP": "Quitter TermTP",
            "view": "Affichage",
            "welcomeTitle": "Bienvenue",
            "welcomeMessage": "Bienvenue dans TermTP\n\nSélectionnez une connexion dans la barre latérale pour démarrer une session SSH.",
            "connectingTo": "Connexion à",
            "connectedTo": "Connecté à",
            "failedToConnect": "Échec de connexion à",
            "noActiveSSHSession": "Aucune session SSH active",
            "sftpUnsupportedForConnection": "Cette connexion ne prend pas en charge la gestion de fichiers SFTP",
            "sftpRefreshFailedFormat": "Échec de l’actualisation des fichiers distants : %@",
            "connectionTimedOutFormat": "Connexion expirée après %@ secondes"
        ],
        .de: [
            "terminalTheme": "Terminal-Design",
            "terminalTheme.classicGreen": "Klassisches Grün",
            "terminalTheme.amber": "Bernstein",
            "terminalTheme.paperWhite": "Papierweiß",
            "terminalTheme.ocean": "Ozean",
            "recent": "Zuletzt",
            "clearHistory": "Verlauf löschen",
            "importConnections": "Importieren",
            "exportConnections": "Exportieren",
            "importConnectionsFailedFormat": "Verbindungen konnten nicht importiert werden: %@",
            "exportConnectionsFailedFormat": "Verbindungen konnten nicht exportiert werden: %@",
            "noConnections": "Keine Verbindungen",
            "addToFavorites": "Zu Favoriten hinzufügen",
            "removeFromFavorites": "Aus Favoriten entfernen",
            "alias": "Kurzname",
            "group": "Gruppe",
            "host": "Host",
            "port": "Port",
            "username": "Benutzername",
            "tags": "Tags",
            "usePrivateKey": "Privaten Schlüssel verwenden",
            "privateKeyPath": "Pfad zum privaten Schlüssel",
            "privateKeyPassphrase": "Passphrase des Schlüssels",
            "password": "Passwort",
            "connection": "Verbindung",
            "keepConnectionAlive": "Verbindung aktiv halten",
            "aliveIntervalSeconds": "Keepalive-Intervall (s)",
            "aliveMaxCount": "Maximale Keepalive-Anzahl",
            "jumpHost": "Jump-Host",
            "defaultRemotePath": "Standard-Remotepfad",
            "portForwarding": "Portweiterleitung",
            "enableForwarding": "Weiterleitung aktivieren",
            "type": "Typ",
            "local": "Lokal",
            "remote": "Entfernt",
            "dynamic": "Dynamisch",
            "bindAddress": "Bind-Adresse",
            "destinationHost": "Zielhost",
            "destinationPort": "Zielport",
            "trustHostKeyTitle": "SSH-Hostschlüssel vertrauen?",
            "reject": "Ablehnen",
            "trust": "Vertrauen",
            "toggleConnections": "Verbindungen ein-/ausblenden",
            "toggleSFTPDrawer": "SFTP-Bereich ein-/ausblenden",
            "commandSnippets": "Befehlsbausteine",
            "listFiles": "Dateien auflisten",
            "diskUsage": "Festplattennutzung",
            "memoryUsage": "Speichernutzung",
            "processMonitor": "Prozessmonitor",
            "serverStatus": "Serverstatus",
            "smallerFont": "Schrift kleiner",
            "largerFont": "Schrift größer",
            "fontSize": "Schriftgröße",
            "refresh": "Aktualisieren",
            "parentDirectory": "Übergeordneter Ordner",
            "remotePath": "Remotepfad",
            "newFolder": "Neuer Ordner",
            "rename": "Umbenennen",
            "name": "Name",
            "open": "Öffnen",
            "done": "Fertig",
            "failed": "Fehlgeschlagen",
            "cancelled": "Abgebrochen",
            "queued": "Wartend",
            "running": "Läuft",
            "retry": "Erneut versuchen",
            "renameTab": "Tab umbenennen",
            "title": "Titel",
            "close": "Schließen",
            "copy": "Kopieren",
            "paste": "Einfügen",
            "showTermTP": "TermTP anzeigen",
            "quitTermTP": "TermTP beenden",
            "view": "Ansicht",
            "welcomeTitle": "Willkommen",
            "welcomeMessage": "Willkommen bei TermTP\n\nWählen Sie links eine Verbindung aus, um eine SSH-Sitzung zu starten.",
            "connectingTo": "Verbinde mit",
            "connectedTo": "Verbunden mit",
            "failedToConnect": "Keine Verbindung zu",
            "noActiveSSHSession": "Keine aktive SSH-Sitzung",
            "sftpUnsupportedForConnection": "Diese Verbindung unterstützt keine SFTP-Dateiverwaltung",
            "sftpRefreshFailedFormat": "Remotedateien konnten nicht aktualisiert werden: %@",
            "connectionTimedOutFormat": "Verbindung nach %@ Sekunden abgelaufen"
        ],
        .ru: [
            "terminalTheme": "Тема терминала",
            "terminalTheme.classicGreen": "Классический зелёный",
            "terminalTheme.amber": "Янтарная",
            "terminalTheme.paperWhite": "Бумажно-белая",
            "terminalTheme.ocean": "Океан",
            "recent": "Недавние",
            "clearHistory": "Очистить историю",
            "importConnections": "Импорт",
            "exportConnections": "Экспорт",
            "importConnectionsFailedFormat": "Не удалось импортировать подключения: %@",
            "exportConnectionsFailedFormat": "Не удалось экспортировать подключения: %@",
            "noConnections": "Нет подключений",
            "addToFavorites": "Добавить в избранное",
            "removeFromFavorites": "Удалить из избранного",
            "alias": "Псевдоним",
            "group": "Группа",
            "host": "Хост",
            "port": "Порт",
            "username": "Имя пользователя",
            "tags": "Теги",
            "usePrivateKey": "Использовать приватный ключ",
            "privateKeyPath": "Путь к приватному ключу",
            "privateKeyPassphrase": "Парольная фраза ключа",
            "password": "Пароль",
            "connection": "Подключение",
            "keepConnectionAlive": "Поддерживать подключение",
            "aliveIntervalSeconds": "Интервал keepalive (с)",
            "aliveMaxCount": "Макс. число keepalive",
            "jumpHost": "Промежуточный хост",
            "defaultRemotePath": "Удалённый путь по умолчанию",
            "portForwarding": "Перенаправление портов",
            "enableForwarding": "Включить проброс",
            "type": "Тип",
            "local": "Локальный",
            "remote": "Удалённый",
            "dynamic": "Динамический",
            "bindAddress": "Адрес прослушивания",
            "destinationHost": "Хост назначения",
            "destinationPort": "Порт назначения",
            "trustHostKeyTitle": "Доверять SSH-ключу хоста?",
            "reject": "Отклонить",
            "trust": "Доверять",
            "toggleConnections": "Показать/скрыть подключения",
            "toggleSFTPDrawer": "Показать/скрыть панель SFTP",
            "commandSnippets": "Фрагменты команд",
            "listFiles": "Список файлов",
            "diskUsage": "Использование диска",
            "memoryUsage": "Использование памяти",
            "processMonitor": "Монитор процессов",
            "serverStatus": "Состояние сервера",
            "smallerFont": "Уменьшить шрифт",
            "largerFont": "Увеличить шрифт",
            "fontSize": "Размер шрифта",
            "refresh": "Обновить",
            "parentDirectory": "Родительская папка",
            "remotePath": "Удалённый путь",
            "newFolder": "Новая папка",
            "rename": "Переименовать",
            "name": "Имя",
            "open": "Открыть",
            "done": "Готово",
            "failed": "Ошибка",
            "cancelled": "Отменено",
            "queued": "В очереди",
            "running": "Выполняется",
            "retry": "Повторить",
            "renameTab": "Переименовать вкладку",
            "title": "Заголовок",
            "close": "Закрыть",
            "copy": "Копировать",
            "paste": "Вставить",
            "showTermTP": "Показать TermTP",
            "quitTermTP": "Завершить TermTP",
            "view": "Вид",
            "welcomeTitle": "Добро пожаловать",
            "welcomeMessage": "Добро пожаловать в TermTP\n\nВыберите подключение на боковой панели, чтобы начать SSH-сеанс.",
            "connectingTo": "Подключение к",
            "connectedTo": "Подключено к",
            "failedToConnect": "Не удалось подключиться к",
            "noActiveSSHSession": "Нет активного SSH-сеанса",
            "sftpUnsupportedForConnection": "Это подключение не поддерживает управление файлами SFTP",
            "sftpRefreshFailedFormat": "Не удалось обновить удалённые файлы: %@",
            "connectionTimedOutFormat": "Время подключения истекло через %@ секунд"
        ],
        .pt: [
            "terminalTheme": "Tema do terminal",
            "terminalTheme.classicGreen": "Verde clássico",
            "terminalTheme.amber": "Âmbar",
            "terminalTheme.paperWhite": "Branco papel",
            "terminalTheme.ocean": "Oceano",
            "recent": "Recentes",
            "clearHistory": "Limpar histórico",
            "importConnections": "Importar",
            "exportConnections": "Exportar",
            "importConnectionsFailedFormat": "Falha ao importar conexões: %@",
            "exportConnectionsFailedFormat": "Falha ao exportar conexões: %@",
            "noConnections": "Sem conexões",
            "addToFavorites": "Adicionar aos favoritos",
            "removeFromFavorites": "Remover dos favoritos",
            "alias": "Apelido",
            "group": "Grupo",
            "host": "Host",
            "port": "Porta",
            "username": "Nome de usuário",
            "tags": "Etiquetas",
            "usePrivateKey": "Usar chave privada",
            "privateKeyPath": "Caminho da chave privada",
            "privateKeyPassphrase": "Frase secreta da chave",
            "password": "Senha",
            "connection": "Conexão",
            "keepConnectionAlive": "Manter conexão ativa",
            "aliveIntervalSeconds": "Intervalo de atividade (s)",
            "aliveMaxCount": "Máximo de atividade",
            "jumpHost": "Servidor de salto",
            "defaultRemotePath": "Caminho remoto padrão",
            "portForwarding": "Encaminhamento de portas",
            "enableForwarding": "Ativar encaminhamento",
            "type": "Tipo",
            "local": "Local",
            "remote": "Remoto",
            "dynamic": "Dinâmico",
            "bindAddress": "Endereço de escuta",
            "destinationHost": "Host de destino",
            "destinationPort": "Porta de destino",
            "trustHostKeyTitle": "Confiar na chave SSH do host?",
            "reject": "Rejeitar",
            "trust": "Confiar",
            "toggleConnections": "Mostrar/Ocultar conexões",
            "toggleSFTPDrawer": "Mostrar/Ocultar painel SFTP",
            "commandSnippets": "Trechos de comando",
            "listFiles": "Listar arquivos",
            "diskUsage": "Uso do disco",
            "memoryUsage": "Uso de memória",
            "processMonitor": "Monitor de processos",
            "serverStatus": "Estado do servidor",
            "smallerFont": "Reduzir fonte",
            "largerFont": "Aumentar fonte",
            "fontSize": "Tamanho da fonte",
            "refresh": "Atualizar",
            "parentDirectory": "Pasta superior",
            "remotePath": "Caminho remoto",
            "newFolder": "Nova pasta",
            "rename": "Renomear",
            "name": "Nome",
            "open": "Abrir",
            "done": "Concluído",
            "failed": "Falhou",
            "cancelled": "Cancelado",
            "queued": "Na fila",
            "running": "Em execução",
            "retry": "Tentar novamente",
            "renameTab": "Renomear aba",
            "title": "Título",
            "close": "Fechar",
            "copy": "Copiar",
            "paste": "Colar",
            "showTermTP": "Mostrar TermTP",
            "quitTermTP": "Sair do TermTP",
            "view": "Visualização",
            "welcomeTitle": "Bem-vindo",
            "welcomeMessage": "Bem-vindo ao TermTP\n\nSelecione uma conexão na barra lateral para iniciar uma sessão SSH.",
            "connectingTo": "Conectando a",
            "connectedTo": "Conectado a",
            "failedToConnect": "Falha ao conectar a",
            "noActiveSSHSession": "Nenhuma sessão SSH ativa",
            "sftpUnsupportedForConnection": "Esta conexão não oferece suporte ao gerenciamento de arquivos SFTP",
            "sftpRefreshFailedFormat": "Falha ao atualizar arquivos remotos: %@",
            "connectionTimedOutFormat": "A conexão expirou após %@ segundos"
        ]
    ]

    static let values: [AppLanguage: [String: String]] = [
        .zhHans: [
            "settings": "设置",
            "language": "语言",
            "terminalTheme": "终端主题",
            "security": "安全",
            "trustedHostKeys": "已信任主机密钥",
            "noTrustedHostKeys": "暂无已信任主机",
            "clearTrustedHostKeys": "清空主机密钥",
            "terminalTheme.classicGreen": "经典黑绿",
            "terminalTheme.amber": "琥珀",
            "terminalTheme.paperWhite": "纸白",
            "terminalTheme.ocean": "海洋",
            "newConnection": "新建连接",
            "cancel": "取消",
            "ok": "确定",
            "connect": "连接",
            "connections": "连接",
            "search": "搜索",
            "recent": "最近",
            "favorites": "收藏",
            "history": "历史",
            "clearHistory": "清空历史",
            "importConnections": "导入",
            "exportConnections": "导出",
            "importConnectionsFailedFormat": "导入连接失败：%@",
            "exportConnectionsFailedFormat": "导出连接失败：%@",
            "noConnections": "暂无连接",
            "addToFavorites": "加入收藏",
            "removeFromFavorites": "取消收藏",
            "delete": "删除",
            "alias": "别名",
            "group": "分组",
            "host": "主机",
            "port": "端口",
            "username": "用户名",
            "tags": "标签",
            "usePrivateKey": "使用私钥",
            "privateKeyPath": "私钥路径",
            "privateKeyPassphrase": "私钥密码",
            "password": "密码",
            "connection": "连接",
            "keepConnectionAlive": "保持连接",
            "aliveIntervalSeconds": "保活间隔秒数",
            "aliveMaxCount": "保活最大次数",
            "jumpHost": "跳板机",
            "defaultRemotePath": "默认远程目录",
            "portForwarding": "端口转发",
            "enableForwarding": "启用转发",
            "type": "类型",
            "local": "本地",
            "remote": "远程",
            "dynamic": "动态",
            "bindAddress": "绑定地址",
            "destinationHost": "目标主机",
            "destinationPort": "目标端口",
            "trustHostKeyTitle": "信任 SSH 主机密钥？",
            "reject": "拒绝",
            "trust": "信任",
            "toggleConnections": "显示/隐藏连接栏",
            "toggleSFTPDrawer": "显示/隐藏 SFTP 面板",
            "commandSnippets": "命令片段",
            "listFiles": "列出文件",
            "diskUsage": "磁盘使用",
            "memoryUsage": "内存使用",
            "processMonitor": "进程监控",
            "serverStatus": "服务器状态",
            "smallerFont": "减小字体",
            "largerFont": "增大字体",
            "fontSize": "字体大小",
            "refresh": "刷新",
            "parentDirectory": "上级目录",
            "remotePath": "远程路径",
            "uploadHere": "上传到这里",
            "newFolder": "新建文件夹",
            "rename": "重命名",
            "name": "名称",
            "open": "打开",
            "download": "下载",
            "preview": "预览",
            "changePermissions": "修改权限",
            "permissions": "权限",
            "invalidPermissions": "权限格式无效，请输入 644 或 755 这样的八进制数字",
            "previewFailedFormat": "预览失败：%@",
            "permissionsChangeFailedFormat": "修改权限失败：%@",
            "choosePrivateKey": "选择私钥",
            "done": "完成",
            "failed": "失败",
            "cancelled": "已取消",
            "queued": "排队中",
            "running": "传输中",
            "retry": "重试",
            "transfers": "传输",
            "clearFinishedTransfers": "清理已完成",
            "secondsRemainingFormat": "剩余 %d 秒",
            "minutesSecondsRemainingFormat": "剩余 %d:%02d",
            "renameTab": "重命名标签页",
            "title": "标题",
            "close": "关闭",
            "copy": "复制",
            "paste": "粘贴",
            "confirmMultilinePasteTitle": "粘贴多行命令？",
            "confirmMultilinePasteMessage": "剪贴板包含多行内容，粘贴后可能立即执行多条命令。",
            "showTermTP": "显示 TermTP",
            "quitTermTP": "退出 TermTP",
            "view": "视图",
            "welcomeTitle": "欢迎",
            "welcomeMessage": "欢迎使用 TermTP\n\n从连接栏选择主机开始 SSH 会话。",
            "connectingTo": "正在连接",
            "connectedTo": "已连接到",
            "failedToConnect": "连接失败",
            "noActiveSSHSession": "没有可用的 SSH 会话",
            "sftpUnsupportedForConnection": "当前连接暂不支持 SFTP 文件管理",
            "sftpRefreshFailedFormat": "刷新远程文件失败：%@",
            "connectionTimedOutFormat": "连接超时，已等待 %@ 秒"
        ],
        .en: [
            "settings": "Settings",
            "language": "Language",
            "terminalTheme": "Terminal Theme",
            "security": "Security",
            "trustedHostKeys": "Trusted Host Keys",
            "noTrustedHostKeys": "No trusted hosts",
            "clearTrustedHostKeys": "Clear Host Keys",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "newConnection": "New Connection",
            "cancel": "Cancel",
            "ok": "OK",
            "connect": "Connect",
            "connections": "Connections",
            "search": "Search",
            "recent": "Recent",
            "favorites": "Favorites",
            "history": "History",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "delete": "Delete",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "uploadHere": "Upload Here",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "download": "Download",
            "preview": "Preview",
            "changePermissions": "Change Permissions",
            "permissions": "Permissions",
            "invalidPermissions": "Invalid permissions. Use an octal value like 644 or 755.",
            "previewFailedFormat": "Preview failed: %@",
            "permissionsChangeFailedFormat": "Failed to change permissions: %@",
            "choosePrivateKey": "Choose Private Key",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transfers",
            "clearFinishedTransfers": "Clear finished",
            "secondsRemainingFormat": "%d s left",
            "minutesSecondsRemainingFormat": "%d:%02d left",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Paste multiple lines?",
            "confirmMultilinePasteMessage": "The clipboard contains multiple lines and may run several commands immediately.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .ja: [
            "settings": "設定",
            "language": "言語",
            "security": "セキュリティ",
            "trustedHostKeys": "信頼済みホスト鍵",
            "noTrustedHostKeys": "信頼済みホストなし",
            "clearTrustedHostKeys": "ホスト鍵を消去",
            "newConnection": "新規接続",
            "cancel": "キャンセル",
            "ok": "OK",
            "connect": "接続",
            "connections": "接続",
            "search": "検索",
            "favorites": "お気に入り",
            "history": "履歴",
            "delete": "削除",
            "download": "ダウンロード",
            "uploadHere": "ここにアップロード",
            "preview": "プレビュー",
            "changePermissions": "権限を変更",
            "permissions": "権限",
            "invalidPermissions": "権限形式が無効です。644 や 755 のように入力してください。",
            "previewFailedFormat": "プレビュー失敗: %@",
            "permissionsChangeFailedFormat": "権限変更失敗: %@",
            "choosePrivateKey": "秘密鍵を選択",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "転送",
            "clearFinishedTransfers": "完了を消去",
            "secondsRemainingFormat": "残り %d 秒",
            "minutesSecondsRemainingFormat": "残り %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "複数行を貼り付けますか？",
            "confirmMultilinePasteMessage": "クリップボードに複数行が含まれ、複数のコマンドがすぐ実行される可能性があります。",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .ko: [
            "settings": "설정",
            "language": "언어",
            "security": "보안",
            "trustedHostKeys": "신뢰한 호스트 키",
            "noTrustedHostKeys": "신뢰한 호스트 없음",
            "clearTrustedHostKeys": "호스트 키 지우기",
            "newConnection": "새 연결",
            "cancel": "취소",
            "ok": "확인",
            "connect": "연결",
            "connections": "연결",
            "search": "검색",
            "favorites": "즐겨찾기",
            "history": "기록",
            "delete": "삭제",
            "download": "다운로드",
            "uploadHere": "여기에 업로드",
            "preview": "미리보기",
            "changePermissions": "권한 변경",
            "permissions": "권한",
            "invalidPermissions": "권한 형식이 잘못되었습니다. 644 또는 755처럼 입력하세요.",
            "previewFailedFormat": "미리보기 실패: %@",
            "permissionsChangeFailedFormat": "권한 변경 실패: %@",
            "choosePrivateKey": "개인 키 선택",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "전송",
            "clearFinishedTransfers": "완료 항목 지우기",
            "secondsRemainingFormat": "%d초 남음",
            "minutesSecondsRemainingFormat": "%d:%02d 남음",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "여러 줄을 붙여넣을까요?",
            "confirmMultilinePasteMessage": "클립보드에 여러 줄이 있어 여러 명령이 즉시 실행될 수 있습니다.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .es: [
            "settings": "Configuración",
            "language": "Idioma",
            "security": "Seguridad",
            "trustedHostKeys": "Claves de host confiables",
            "noTrustedHostKeys": "Sin hosts confiables",
            "clearTrustedHostKeys": "Borrar claves de host",
            "newConnection": "Nueva conexión",
            "cancel": "Cancelar",
            "ok": "Aceptar",
            "connect": "Conectar",
            "connections": "Conexiones",
            "search": "Buscar",
            "favorites": "Favoritos",
            "history": "Historial",
            "delete": "Eliminar",
            "download": "Descargar",
            "uploadHere": "Subir aquí",
            "preview": "Vista previa",
            "changePermissions": "Cambiar permisos",
            "permissions": "Permisos",
            "invalidPermissions": "Permisos no válidos. Usa un valor octal como 644 o 755.",
            "previewFailedFormat": "Error de vista previa: %@",
            "permissionsChangeFailedFormat": "No se pudieron cambiar los permisos: %@",
            "choosePrivateKey": "Elegir clave privada",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transferencias",
            "clearFinishedTransfers": "Limpiar terminadas",
            "secondsRemainingFormat": "Quedan %d s",
            "minutesSecondsRemainingFormat": "Quedan %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "¿Pegar varias líneas?",
            "confirmMultilinePasteMessage": "El portapapeles contiene varias líneas y puede ejecutar varios comandos de inmediato.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .fr: [
            "settings": "Réglages",
            "language": "Langue",
            "security": "Sécurité",
            "trustedHostKeys": "Clés d’hôte approuvées",
            "noTrustedHostKeys": "Aucun hôte approuvé",
            "clearTrustedHostKeys": "Effacer les clés d’hôte",
            "newConnection": "Nouvelle connexion",
            "cancel": "Annuler",
            "ok": "OK",
            "connect": "Connexion",
            "connections": "Connexions",
            "search": "Rechercher",
            "favorites": "Favoris",
            "history": "Historique",
            "delete": "Supprimer",
            "download": "Télécharger",
            "uploadHere": "Téléverser ici",
            "preview": "Aperçu",
            "changePermissions": "Modifier les permissions",
            "permissions": "Permissions",
            "invalidPermissions": "Permissions invalides. Utilisez une valeur octale comme 644 ou 755.",
            "previewFailedFormat": "Échec de l’aperçu : %@",
            "permissionsChangeFailedFormat": "Échec du changement de permissions : %@",
            "choosePrivateKey": "Choisir une clé privée",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transferts",
            "clearFinishedTransfers": "Effacer terminés",
            "secondsRemainingFormat": "%d s restantes",
            "minutesSecondsRemainingFormat": "%d:%02d restantes",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Coller plusieurs lignes ?",
            "confirmMultilinePasteMessage": "Le presse-papiers contient plusieurs lignes et peut exécuter plusieurs commandes immédiatement.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .de: [
            "settings": "Einstellungen",
            "language": "Sprache",
            "security": "Sicherheit",
            "trustedHostKeys": "Vertrauenswürdige Hostschlüssel",
            "noTrustedHostKeys": "Keine vertrauenswürdigen Hosts",
            "clearTrustedHostKeys": "Hostschlüssel löschen",
            "newConnection": "Neue Verbindung",
            "cancel": "Abbrechen",
            "ok": "OK",
            "connect": "Verbinden",
            "connections": "Verbindungen",
            "search": "Suchen",
            "favorites": "Favoriten",
            "history": "Verlauf",
            "delete": "Löschen",
            "download": "Herunterladen",
            "uploadHere": "Hier hochladen",
            "preview": "Vorschau",
            "changePermissions": "Berechtigungen ändern",
            "permissions": "Berechtigungen",
            "invalidPermissions": "Ungültige Berechtigungen. Verwende einen Oktalwert wie 644 oder 755.",
            "previewFailedFormat": "Vorschau fehlgeschlagen: %@",
            "permissionsChangeFailedFormat": "Berechtigungen konnten nicht geändert werden: %@",
            "choosePrivateKey": "Privaten Schlüssel wählen",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Übertragungen",
            "clearFinishedTransfers": "Fertige löschen",
            "secondsRemainingFormat": "%d s übrig",
            "minutesSecondsRemainingFormat": "%d:%02d übrig",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Mehrere Zeilen einfügen?",
            "confirmMultilinePasteMessage": "Die Zwischenablage enthält mehrere Zeilen und kann sofort mehrere Befehle ausführen.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .ru: [
            "settings": "Настройки",
            "language": "Язык",
            "security": "Безопасность",
            "trustedHostKeys": "Доверенные ключи хостов",
            "noTrustedHostKeys": "Нет доверенных хостов",
            "clearTrustedHostKeys": "Очистить ключи хостов",
            "newConnection": "Новое подключение",
            "cancel": "Отмена",
            "ok": "OK",
            "connect": "Подключить",
            "connections": "Подключения",
            "search": "Поиск",
            "favorites": "Избранное",
            "history": "История",
            "delete": "Удалить",
            "download": "Скачать",
            "uploadHere": "Загрузить сюда",
            "preview": "Просмотр",
            "changePermissions": "Изменить права",
            "permissions": "Права",
            "invalidPermissions": "Неверный формат прав. Используйте восьмеричное значение, например 644 или 755.",
            "previewFailedFormat": "Ошибка просмотра: %@",
            "permissionsChangeFailedFormat": "Не удалось изменить права: %@",
            "choosePrivateKey": "Выбрать приватный ключ",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Передачи",
            "clearFinishedTransfers": "Очистить завершённые",
            "secondsRemainingFormat": "Осталось %d с",
            "minutesSecondsRemainingFormat": "Осталось %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Вставить несколько строк?",
            "confirmMultilinePasteMessage": "Буфер обмена содержит несколько строк и может сразу выполнить несколько команд.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ],
        .pt: [
            "settings": "Definições",
            "language": "Idioma",
            "security": "Segurança",
            "trustedHostKeys": "Chaves de host confiáveis",
            "noTrustedHostKeys": "Nenhum host confiável",
            "clearTrustedHostKeys": "Limpar chaves de host",
            "newConnection": "Nova conexão",
            "cancel": "Cancelar",
            "ok": "OK",
            "connect": "Conectar",
            "connections": "Conexões",
            "search": "Pesquisar",
            "favorites": "Favoritos",
            "history": "Histórico",
            "delete": "Excluir",
            "download": "Baixar",
            "uploadHere": "Enviar aqui",
            "preview": "Pré-visualizar",
            "changePermissions": "Alterar permissões",
            "permissions": "Permissões",
            "invalidPermissions": "Permissões inválidas. Use um valor octal como 644 ou 755.",
            "previewFailedFormat": "Falha na pré-visualização: %@",
            "permissionsChangeFailedFormat": "Falha ao alterar permissões: %@",
            "choosePrivateKey": "Escolher chave privada",
            "terminalTheme": "Terminal Theme",
            "terminalTheme.classicGreen": "Classic Green",
            "terminalTheme.amber": "Amber",
            "terminalTheme.paperWhite": "Paper White",
            "terminalTheme.ocean": "Ocean",
            "recent": "Recent",
            "clearHistory": "Clear History",
            "importConnections": "Import",
            "exportConnections": "Export",
            "importConnectionsFailedFormat": "Failed to import connections: %@",
            "exportConnectionsFailedFormat": "Failed to export connections: %@",
            "noConnections": "No connections",
            "addToFavorites": "Add to Favorites",
            "removeFromFavorites": "Remove from Favorites",
            "alias": "Alias",
            "group": "Group",
            "host": "Host",
            "port": "Port",
            "username": "Username",
            "tags": "Tags",
            "usePrivateKey": "Use private key",
            "privateKeyPath": "Private key path",
            "privateKeyPassphrase": "Private key passphrase",
            "password": "Password",
            "connection": "Connection",
            "keepConnectionAlive": "Keep connection alive",
            "aliveIntervalSeconds": "Alive interval seconds",
            "aliveMaxCount": "Alive max count",
            "jumpHost": "Jump host",
            "defaultRemotePath": "Default remote path",
            "portForwarding": "Port Forwarding",
            "enableForwarding": "Enable forwarding",
            "type": "Type",
            "local": "Local",
            "remote": "Remote",
            "dynamic": "Dynamic",
            "bindAddress": "Bind address",
            "destinationHost": "Destination host",
            "destinationPort": "Destination port",
            "trustHostKeyTitle": "Trust SSH Host Key?",
            "reject": "Reject",
            "trust": "Trust",
            "toggleConnections": "Toggle Connections",
            "toggleSFTPDrawer": "Toggle SFTP Drawer",
            "commandSnippets": "Command Snippets",
            "listFiles": "List files",
            "diskUsage": "Disk usage",
            "memoryUsage": "Memory usage",
            "processMonitor": "Process monitor",
            "serverStatus": "Server status",
            "smallerFont": "Smaller Font",
            "largerFont": "Larger Font",
            "fontSize": "Font Size",
            "refresh": "Refresh",
            "parentDirectory": "Parent Directory",
            "remotePath": "Remote path",
            "newFolder": "New Folder",
            "rename": "Rename",
            "name": "Name",
            "open": "Open",
            "done": "Done",
            "failed": "Failed",
            "cancelled": "Cancelled",
            "queued": "Queued",
            "running": "Running",
            "retry": "Retry",
            "transfers": "Transferências",
            "clearFinishedTransfers": "Limpar concluídas",
            "secondsRemainingFormat": "Restam %d s",
            "minutesSecondsRemainingFormat": "Restam %d:%02d",
            "renameTab": "Rename Tab",
            "title": "Title",
            "close": "Close",
            "copy": "Copy",
            "paste": "Paste",
            "confirmMultilinePasteTitle": "Colar várias linhas?",
            "confirmMultilinePasteMessage": "A área de transferência contém várias linhas e pode executar vários comandos imediatamente.",
            "showTermTP": "Show TermTP",
            "quitTermTP": "Quit TermTP",
            "view": "View",
            "welcomeTitle": "Welcome",
            "welcomeMessage": "Welcome to TermTP\n\nSelect a connection from the sidebar to start an SSH session.",
            "connectingTo": "Connecting to",
            "connectedTo": "Connected to",
            "failedToConnect": "Failed to connect to",
            "noActiveSSHSession": "No active SSH session",
            "sftpUnsupportedForConnection": "SFTP file management is not supported for this connection",
            "sftpRefreshFailedFormat": "Failed to refresh remote files: %@",
            "connectionTimedOutFormat": "Connection timed out after %@ seconds"
        ]
    ]
}
